# Standard JSON Schema declaration.
$schema: "https://json-schema.org/draft/2020-12/schema"
$path: "example.com/schema.yaml"

$intent: >
  Defines the structure for the root 'repo' atom. This is the schema
  for the seed that represents the entire repository itself.

type: object
required: ['$path', id, kind, intent, state, spec]
properties:
  '$path':
    const: "example.com/seed.yaml"
  id:
    const: "seed://example.com.v1"
  kind:
    const: "repo"
  intent:
    type: object
    properties:
      goal:
        const: "To contain and evolve a self-describing digital organism."
      role:
        const: "The root cell and container for the entire system."
  state:
    type: object
  links:
    type: array
  io:
    type: object
  spec:
    type: object
    properties:
      schema:
        const: "example.com/schema.yaml"
      layout:
        type: object
        properties:
          strict: { type: "boolean" }
          files: { type: "array", items: { type: "string" } }
          dirs: { type: "array", items: { type: "string" } }
